version: '2'

services:
  nginx:
    ports:
      - 443:443
    volumes:
      - ${VOLUME_DIRECTORY}/vhosts:/etc/nginx/vhost.d
      - ${VOLUME_DIRECTORY}/certs:/etc/nginx/certs

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-server__letsencrypt
    command: -notify-sighup proxy-server__nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLUME_DIRECTORY}/certs:/etc/nginx/certs
    networks:
      - ${NETWORK_NAME}