version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: proxy-server__nginx
    environment:
      ENABLE_IPV6: 'true'
      DEFAULT_HOST: ${DEFAULT_HOST}
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
    volumes:
      - /etc/nginx/conf.d
      - /usr/share/nginx/html
    networks:
      - ${NETWORK_NAME}

  dockergen:
    image: jwilder/docker-gen
    container_name: proxy-server__dockergen
    command: -notify-sighup proxy-server__nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    volumes_from:
      - nginx
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - ${NETWORK_NAME}

networks:
  proxy-server:
    external: true